### ISSUE TITLE
can this camera work with mjpg-streamer on an raspberry?

### ISSUE THREAD

**Issue by TylonHH** [samtap/fang-hacks#103]
Hi,
I couldn't find the information in the specs or else, but you guys are more into it.
I wanna know if this cam work with [mjpg-streamer](https://github.com/foosel/OctoPrint/wiki/MJPG-Streamer-configuration) on a raspberry(3)? I wanna use this nice cam for my 3D printer with [OctoPi](https://github.com/foosel/OctoPrint/wiki/Webcams-known-to-work).

Cheers

**Comment by samtap** [comment]
No, mjpg-streamer supports local USB devices or rpi camera module, not ip camera with rtsp stream
