### ISSUE TITLE
Request: info on how to do something similar with different camera

### ISSUE THREAD

**Issue by jschwalbe** [samtap/fang-hacks#106]
Hi - first of all, I'm sorry, this isn't an issue with this specific software, but I don't know how else to contact you.

I am trying to do what you did (create an RTSP server) with another closed box system camera (https://www.walmart.com/ip/Minion-Stuart-Cam-HD-Wifi-Camera-Walmart-Exclusive/54905488). So far I've been able to grab the firmware via an update and I've been able to get root, but not much else. It's running Busybox on an ARM7vl (I believe) processor.

I'm not sure the next step to getting it to run an RTSP server. Can you point me in any directions? 

A contact address for me is: my username on google's mail servers, or replying here is fine with me if it's okay with everyone else.

**Comment by samtap** [comment]
We were lucky to find source-code for the SNX chip. Most of these devices use proprietary 'low-level' software taking advantage of hardware acceleration, the cpu is way too limited to handle video with 'high-level' software like ffmpeg, gstreamer. So the next step is using your root access to find out details about the hardware and then finding, modifying or writing from scratch the RTSP server.

Feel free to join the discord chat, there's a nice group of people all with similar interests (I've no problem discussing other cameras/devices besides the xiaofang there)
