### ISSUE TITLE
 see rtsp  streaming outside WI-FI

### ISSUE THREAD

**Issue by Pierinopower** [samtap/fang-hacks#107]
Hi, i tried to open port 554 on my router for see by smartphone my Xiaomi cam outside home wi-fi, but I can't see rtsp streaming outside. Maybe i need to open another port? thank you, and sorry for my bad english

**Comment by samtap** [comment]
No other port is required, though I recommend forwarding port 22 (ssh) and using a tunnel for port 554, so you won't open up your rtsp stream for anyone on the internet.

Closing this as it's not an issue. Please join discord chat for support.
