### ISSUE TITLE
NFS mount works just fine

### ISSUE THREAD

**Issue by desidude2000** [samtap/fang-hacks#113]
Not sure where and how to post ideas.    Issues area seems to be the most active area.  In any case, NFS client capabilities are built-in to the original firmware.   After one telnets into the camera, one can:

~ # mount -t nfs -o nolock 192.168.0.109:/data /mnt

Works fine for me.    Opens up new possibilities with chroot to a NFS mounted directory.

**Comment by samtap** [comment]
Yes I'm aware of this, the Wiki is the best place to add more info: https://github.com/samtap/fang-hacks/wiki/Using-NFS-to-extend-storage-options
