### ISSUE TITLE
HELPME PLS 

### ISSUE THREAD

**Issue by tolga1612** [samtap/fang-hacks#117]
My device is setting up a wifi connection but the blue light is blinking No read sd card

Only reads the memory card in yellow light
![screenshot1](https://cloud.githubusercontent.com/assets/13822897/25557452/321cb4f4-2d1a-11e7-823e-0c89e9aa7911.png)
![screenshot2](https://cloud.githubusercontent.com/assets/13822897/25557492/083a01ae-2d1b-11e7-8470-a371d56bfe67.png)

**Comment by samtap** [comment]
Please don't create duplicate issues....
