### ISSUE TITLE
Is it possible to disable cloud feature?

### ISSUE THREAD

**Issue by streetlight123** [samtap/fang-hacks#12]
Is it possible to disable the xiaomi cloud feature and use our local network?

**Comment by tobilap** [comment]
Yeah, thats what this project is about. It disables the cloud and gives you control over the camera. By default a rtsp stream is started. All you need is and app or a software which can handle rtsp streams (e.g. VLC )

**Comment by samtap** [comment]
If you mean completely disable it instead of killing it after 30 secs when wifi is up like it's done now, see #1
