### ISSUE TITLE
Possible to run without SDHC card?

### ISSUE THREAD

**Issue by milesburton** [samtap/fang-hacks#120]
These cameras have been absolutely superb - is there a recommended way to write the appropriate files directly to the onboard flash, only using SDHC in emergencies?

**Comment by samtap** [comment]
There is no 'recommended' way or any support for it, but it's possible. There's just not much room but you could run the rtsp server from flash. Busybox, dropbear etc. have not been built for minimal deployment though so you will lose these (they're also built with some hacks to support running off sdcard so they probably won't even work when copied to flash). I suggest taking a look at /etc/init.d/rcS and /etc/init.d/rc.local, removing anything there related to fang-hacks and running snx_rtsp_server directly.
As you're messing with flash you should be prepared for locking yourself out, make sure you're able to recover i.e. by flashing recovery firmware or using serial console.

**Comment by zecoj** [comment]
In case anyone is still interested in pursuing this option, I've made some progress on this and can be found here: https://github.com/zecoj/fang-hacks-internal
