### ISSUE TITLE
Is It possible to adjust brightness and contrast?

### ISSUE THREAD

**Issue by Cosby86** [samtap/fang-hacks#128]
Hey there,
Is It possible to adjust brightness and contrast?

Thanks

**Comment by samtap** [comment]
You can change a lot of settings with snx_isp_ctl, which is in the test folder (/media/mmcblk0p2/data/test). There's no webpage yet to control it or make it permanent. For the time being you need to create your own script, or add the commands to i.e. the rtsp server script (/media/mmcblk0p2/data/etc/scripts/20-rtsp-server)

**Comment by Cosby86** [comment]
Got it. Thank you

**Comment by joesphan** [comment]
Is there documentation on the commands with snx_isp_ctl? I figured out the rotate and mirror commands, but not the brightness/contrast commands

Thanks!
