### ISSUE TITLE
iSmartalarm Spot

### ISSUE THREAD

**Issue by mh2370** [samtap/fang-hacks#13]
Hi,
Is it possible to make work this Xiaofang camera with the iSmartalarm app
Because it is the same camera as the iSmartalarm Spot

https://www.ismartalarm.com/devices/cameras/spot/isa00013.html

Maybe with an edited firmware?

Thanks

**Comment by Gilgameshismist** [comment]
Is not possible without the original iSmartalarm firmware. (which currently isn't available).

**Comment by mh2370** [comment]
Ok i didn't know that
Hopefully can it be installed in the future
The iSmartalarm app is really nice

**Comment by snailium** [comment]
I'm able to find iSmartAlarm firmware v2.4.9.6, which seems to be the latest. It is from Android app.

I uploaded the firmware here.
https://1drv.ms/u/s!AjUVjow4El8Wn7MHpB6e5KZm1H-hYg

@samtap Please take a look if you have time. :)

**Comment by Swiftnesses** [comment]
Amazing find, can we get this firmware uploaded to the camera and use it with the app?
