### ISSUE TITLE
Change time to show correct time

### ISSUE THREAD

**Issue by leas1968** [samtap/fang-hacks#141]
Is it possible to change the time to show the correct time in the right timezone? Even if I change the time zone time stays in the default time zone.

**Comment by keith721** [comment]
From the FAQ item in the wiki, visit [this link](http://svn.fonosfera.org/fon-ng/trunk/luci/modules/admin-fon/root/etc/timezones.db) and select your timezone specification from the list for Europe.  The format to enter in the Status web page should appear like this: 

    EET-2EEST,M3.5.0/3,M10.5.0/4
    CET-1CEST,M3.5.0,M10.5.0/3
    GMT0BST,M3.5.0/1,M10.5.0

**Comment by leas1968** [comment]
Thank you very much, Keith! I will try this!
