### ISSUE TITLE
720p?

### ISSUE THREAD

**Issue by pjpalomaki** [samtap/fang-hacks#143]
Hi, I've managed to install the hacks and everything runs fine. The problem is that viewing the cam via tinyCam gives some dropped frames and generally a bit laggy.

Is there a way to switch the camera to 720p? Or am I doing something wrong for it to have issues with streaming?

**Comment by keith721** [comment]
https://github.com/samtap/fang-hacks/wiki/snx_rtsp_server-help-text

Edit the -W and -H parameter values in the rtsp_server script on the SD card.

**Comment by samtap** [comment]
Assuming resolved
