### ISSUE TITLE
It appears like there is no outside subnet access on FW: 3.0.4.20

### ISSUE THREAD

**Issue by sadamahan** [samtap/fang-hacks#146]
Be careful with firmware: 3.0.4.20. Its only possible to access the fang hack url: /cgi-bin/status when on the same subnet , but not from outside the subnet. Seems like the camera is doing a source IP check. But that restriction does not exist with the previous version of the firmware: 3.0.4.9.  

No NAT'ing or special routing between the two subnets.

Attached tcp dump files for:
Cam1 (working): FW: 3.0.4.9
Cam2 (not working): FW:3.0.4.20 

Both with MAC 34.

TCP dump for both FW:
[FW 3.0.4.20 - no outside subnet access.txt](https://github.com/samtap/fang-hacks/files/1036178/FW.3.0.4.20.-.no.outside.subnet.access.txt)
[FW 3.0.4.9 - outiside subnet access OK.txt](https://github.com/samtap/fang-hacks/files/1036177/FW.3.0.4.9.-.outiside.subnet.access.OK.txt)

**Comment by samtap** [comment]
Thanks, I've moved your comment to #122
