### ISSUE TITLE
Working Android App request

### ISSUE THREAD

**Issue by RafeSl** [samtap/fang-hacks#149]
I'm just wondering what people are using to view the rtsp stream from the camera.

From windows I can happily use VLC but Android (where I am mainly only able to connect from) is causing me issues. I struggle to get a decent uncorrupted stream.
The best one I've found so far is BS Player, but its still unreliable.
VLC crashes pretty much as soon as it connects.

I tried a number of others the night I first got the hacks installed but at this stage I struggle to remember which ones I've tried.

thanks

Rafe

**Comment by ZeroPoints** [comment]
TinyCam Free worked well for me and yea VLC on mobile crashes for me.

**Comment by RafeSl** [comment]
ty. I'll try that.
