### ISSUE TITLE
Hi, ask for help, I've processed it in order, but it's still the following problem. Many services don't open.

### ISSUE THREAD

**Issue by 1043717432** [samtap/fang-hacks#156]
Hi, ask for help, I've processed it in o
![qq 20170604001958](https://cloud.githubusercontent.com/assets/22461690/26755215/913e9db4-48bb-11e7-83f8-2463e3e0b00a.jpg)
![qq 20170604002012](https://cloud.githubusercontent.com/assets/22461690/26755216/9566d91a-48bb-11e7-86ae-b9681e530855.jpg)
![qq 20170604002019](https://cloud.githubusercontent.com/assets/22461690/26755217/971b5268-48bb-11e7-80df-144f9aa16a18.jpg)

rder, but it's still the following problem. Many services don't open.

**Comment by Protocol-IRK** [comment]
See the yes button near top of logo, press that to expand the sd card partition and wait. Takes up to 30mins or more on some larger cards. Once it's complete it will tell you it needs a reboot, do it too early and you will cause problems which will mean you will need to reflash sd card.

**Comment by samtap** [comment]
Please read the other issues or ask for support on discord. After flashing the image all services are supposed to work regardless of filesystem expansion. If it doesn't work try a different sdcard.

**Comment by 1043717432** [comment]
ok
