### ISSUE TITLE
software not fully booting

### ISSUE THREAD

**Issue by fincha** [samtap/fang-hacks#157]
I am not really sure what the problem is but the situation is like following:

I have 3 cams, one is running perfectly, I have an 8gb SD Card with the image from here running. the /status url is reachable and showing content.

My second and third cam, I use the same SD card, which is working for another camera, I have following situation:

blue flashing led (back)
ip is pingable
hello.cgi is working

> snx_autorun.sh
> bootstrap
> System Volume Information
> time_lapse
> record

status is not working

> 404 Not Found
> The requested URL /cgi-bin/status was not found on this server.

any idea on this?

**Comment by Protocol-IRK** [comment]
reflash the sd cards, I had the same issue and other have as well.

**Comment by fincha** [comment]
@Protocol-IRK I have a second sd card, I reflashed it multiple times, also I expect the cam to work with sd card, which is working on different. Anyway... any other ideas?

**Comment by Protocol-IRK** [comment]
Have you a different card to try? I know one card is working however just for argument sake. If that fails to work try the reset button and try again.

you may have a dodge sdcard slot? thus might need to dissemble it and hook up a uart connection, this is speculation.

**Comment by samtap** [comment]
You have to troubleshoot issues like these using telnet/ssh. Check the logfile in /tmp and run commands manually to check for errors. But I agree most likely the sdcard is broken or corrupt.

**Comment by fincha** [comment]
@Protocol-IRK I just tried different sd card (32 gb, same issue)
@samtap somehow there is only port 80 running, accorting the ip scanner, also I can't connect via putty or so...sd card is brand new

**Comment by fincha** [comment]
I also noticed, If I remove the sd card, I can scan the qr code, and later I hear the voice, but I can't connect to the original xiaomi home app any more... might this be a problem with the firmware?
