### ISSUE TITLE
PUSH notifications for iOSPhone

### ISSUE THREAD

**Issue by TDPFlorida** [samtap/fang-hacks#159]
This is not really an issue with the HACK but the camera using the Chinese server so I figured someone may have experienced this and can help.

I have 3 of these Xiaomi 1080 cube cameras running...as well as several Xiaomi Ants Xiaoyi Smart Camera 720. The issue I am having is NOW running MiHome v3.17.0 and even going down to v3.12.0 the PUSH notification NOW include CHINESE time (24 hour HH:MM). I'm certain this is NEW (and because of the Chinese server) and ONLY happens with the 1080 cameras. Since it is Chinese and I am US EST, I would like to get rid of it OR correct it. I did use the HACK to change the TIMESTAMP successfully to US EST but now have the hack disabled. 
Thanks

**Comment by samtap** [comment]
For the osd timstamp, cloud app doesn't use the 'system' time of the camera, but some kind of offset. So if you want the correct time on osd of cloud app, you have to set an 'incorrect' system time...
But this just concerns the osd timestamp, no idea what produces the timestamp in push notifications of mi home. There is no support for mi home here so you should post it on a Xiaomi forum.
