### ISSUE TITLE
What does the setup button to the hack?

### ISSUE THREAD

**Issue by joxer** [samtap/fang-hacks#16]
What does pressing the setup button do to your hack? Does it clear the total sd or just restore the old configurations?

**Comment by samtap** [comment]
As far as I know, the setup button only starts the process to connect with Mi Home using QR code etc, which is all handled by the cloud apps. What makes you think it clears the sd?

**Comment by joxer** [comment]
dunno, it was just a supposition. Do you have a irc channel where you can hang out? it would be cool to discuss about the project or similar projects

**Comment by samtap** [comment]
@joxer I'd be happy to join you on IRC but don't have time to set it up. Perhaps #fanghacks on freenode?

**Comment by joxer** [comment]
Sure! great :)
