### ISSUE TITLE
Unable to use MiHome after hack

### ISSUE THREAD

**Issue by tam481** [samtap/fang-hacks#162]
Hi,
I have not been able to get the camera to work with the Mi Home app since applying the hack. I remove the SD card and reboot the camera to no avail. 

When I remove the SD card I can see that the camera is online but when I tap on it it says "connecting 1/3.." and nothing else.

Please help.

**Comment by samtap** [comment]
This happens for me from time to time, perhaps the cloud server is down or sometimes restarting mi home helps. Either way you should contact Xiaomi for support, it's not related to fang-hacks.
