### ISSUE TITLE
RTSP is being software encoded not hardware

### ISSUE THREAD

**Issue by tam481** [samtap/fang-hacks#163]
Hi,
My camera is still getting quite warm and I've noticed in TinyCam that the stream is being software encoded. It reads H264 SW 20fps, 220 KB/s. Obviously the frame rate and the data rate keep changing but the maximum fps I get is 20.

Thanks in advance

**Comment by ksprelude01** [comment]
In tinycam you have to change your settings to use hardware decoding.
