### ISSUE TITLE
Bricked with orange fixed led

### ISSUE THREAD

**Issue by zekje** [samtap/fang-hacks#166]
Hi,

i Use Xiafoang hack without problems
last day , no video on my nas, i saw that rstpserver on xiaofang was NOK

i have tryed to disable cloud in cfg file and badaboum, xiaomi xiaofang is now bricked ....
i only have the orange led fixed :(

i have tried to soldier an usb port, and i saw this (reboot in loop)

[xiaofang reboot.txt](https://github.com/samtap/fang-hacks/files/1085055/xiaofang.reboot.txt)

I have tyied to instal FIRMWARE_660R on a sdcard, and pushing the button : 

[xiaofang flash.txt](https://github.com/samtap/fang-hacks/files/1085056/xiaofang.flash.txt)

but after flash/boot , it reboot in loop :(

Can anybody help me ?
did my cam is realy died ?

(edit : supresse output and add .txt files for comprehensive )

**Comment by samtap** [comment]
Can you upload a log that shows the reboot loop? Or does it start immediately after the last line? It appears the filesystem is mounted and all looks well, I can only guess at this point but maybe it fails to load the init (linuxrc) process? But normally there should be at least a kernel panic or some other error before it reboots.

**Comment by zekje** [comment]
sorry i'm not at home this week .

yes, the device reboot in loop as you can show in reboot.txt ( after USB lines it restart by Uboot .... )

i have tried to flash firmaware (see the second txt ) but after flashing ( seems to be successful ? ) , it reboot again .... did my firmwarefile is not good ?

did my webcam is out ?

**Comment by diegomtnz** [comment]
> Use at your own risk! It is still possible to break the device, to the point where you'll have to solder some wires to get access to a serial console, or worse. When cloud apps are disabled and WiFi mis-configured or offline you will not be able to access the device, not even by removing the sdcard. The scripts that disable cloud apps and set the network mode are located on the device itself. But don't panic, recovery is possible by placing the right files in the bootstrap folder on the sdcard. If you do find any bugs please let me know!

> 
mi cam is beek when disable cloud too
i only have the orange led fixed

i go to ubuntu
in terminal 

> sudo nautilus

> 
go to media/mmcblk0p2/data/etc/wpa_supplicant.conf

And edit with my wifi data:

> ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
ap_scan=1

network={
	ssid="XXXXXXXX"
	key_mgmt=WPA-PSK
	pairwise=CCMP TKIP
	group=CCMP TKIP WEP104 WEP40
	psk="XXXXXXXX"
	scan_ssid="1"
	priority=2
}
``
config your acces point in:
WPA-PSK
CCMP TKIP
In microSD and power on cam
the orange led continue fixed
but in your router go to lan status to see ip cam
http://device-ip/cgi-bin/status 
and you can config cam

**Comment by zekje** [comment]
after many times on my xiaofang, i have found the problem ..... it's me :p 

USB to serial FTDI provide 3,3v , perfect for serial connection, but not for the webcam
i have disconnected 3,3v, and power by USB (from the same PC for the same ground ) , and ont he serial terminal , it not reboot in loop , and i can connect with serial on the embeded linux ( to modify cloud=1 )
i have flashed firmware to start from 0, and after reboot, the led flash orange ( not stay ), no sound becouse speaker not pluged :p 
i can make wifi connection to the xiaomi app on my phone , and install hack ( already present .... firmware flash will not reset this ) .
my webcam is now online ....

i have an other problem with rstp server seem to hang after a while,  but this issue is closed

**Comment by marceloxlo** [comment]
I've acidently put it in "Download mode" without sd card... now the leds stays fixed orange too :( Is it bricked? how can i solve it?
