### ISSUE TITLE
How to use the camera on external network?

### ISSUE THREAD

**Issue by mp3lll** [samtap/fang-hacks#167]
554 dont working, also i do not fine how to get the file snx_rtsp_server to change the port.

rtsp://MyeXTERNALIP:554/unicast vlc dont working.

what i miss?

/etc/rtsp/snx_rtsp_server  i do not have it

Thanks!

**Comment by samtap** [comment]
I have no idea what you're talking about. Try again with a better description or ask for support on discord chat.
