### ISSUE TITLE
Wirelles connection problem with "large names"

### ISSUE THREAD

**Issue by comeollas** [samtap/fang-hacks#168]
Hi first thanks for your work :)

I tryed in one camera this system and works perfect.

I see one problem i have two wi-fi's in my house one of them called "teknolocia jjiuke S.C.P" if i try to connect in this wi-fi it's imposible to connect, because system take  SSID: teknolocia adress:ijiuke and security S.C.P and say can't connect because don't recognize the security.

Its a problem with space's in wireless i think.

With other Wifi with simple name "TR" all perfect.

Thanks for your fang-hack!!!!

**Comment by samtap** [comment]
Duplicate #52
