### ISSUE TITLE
Wireless network characters

### ISSUE THREAD

**Issue by zackoch** [samtap/fang-hacks#179]
Does the hack not support and apostrophe, like in the word don't, in the SSID? I can't seem to get the camera to swap over from cloud to wireless client... it just hangs and I have to reboot the camera.

Thanks,

**Comment by samtap** [comment]
Did you try the updated network script? https://github.com/samtap/fang-hacks/commit/f3c3fcdf99f2e1ec520e911d6d31149a1075e8c9

**Comment by zackoch** [comment]
I just used the image - is it not in the image release?

**Comment by zackoch** [comment]
Dead 😂
