### ISSUE TITLE
run hot after hours, not stable when hot

### ISSUE THREAD

**Issue by ageorgios** [samtap/fang-hacks#188]
If the Xiaofang runs for a lot of time it becomes hot and the RTSP becomes unstable.

**Comment by wekii** [comment]
You should install hacks from current repository with latest commits, not hacks from latest release.

https://github.com/samtap/fang-hacks/commit/47e320c0fa775bf037a9f664ea008006da2db0e4

**Comment by martiGIT** [comment]
could you please tell us how to upgrade to current repo when this is already installed?

**Comment by samtap** [comment]
You'll have to download and replace this file manually: https://github.com/samtap/fang-hacks/blob/master/data/usr/bin/fang-ir-control.sh (make sure it has the right attributes after copying to device: chmod 755 fang-ir-control.sh)
