### ISSUE TITLE
Mijia firmware 3.3.9_0121 support

### ISSUE THREAD

**Issue by Filipowicz251** [samtap/fang-hacks#190]
Hi

Yesterday i've received my "Xiaomi mijia 1080P Smart IP Camera" I've read about "Fang Hacks" - so i was sure i can enable its "full power"

First of all i've tried to connect camera to my wifi network. There were problem because i've tried to connect it to 5GHZ network and it cannot be connected this way. But it finally worked. At the begining i've tried to use APP, which was downloaded after i scan QR code for application (attached in Guide shipped with camera) It was not successful (because of 5GHZ - i didn't noticed it back then) - then i've tried to download another app called "YI home" But i cannot connect camera with this app either (but i realised it was wrong wifi type) Then i go back to this application from guide (on my iphone - application name is in china - but i've used "google translate" and it is saying it is just "MI" application)

I've moved to second step: "Installing hack to sd card". I've used Win32 Disk Imager (attaching PrtScr)

After saving image to sd card (i'm using sd card adapter for micro sd card - if it's matter) i see two partition created (PrtScr attached) - one is normally display, second one is undiscovered.

[Update] I've installed "Ext2 File System Driver for Windows" - now i can see also the second "data" partition (PrtScr attached)

After that i've insert sd card to camera but... there was no effect. No sound of inserted sim card (as it has been mentioned) Nothing... In Mi application i see - that sd card is being discovered but apparently hack is not being applied (attaching PrtScr)

hxxp://192.168.0.20/cgi-bin/hello.cgi is not working. Of course i've checked - my computer is connected to the same wifi network (not the 5 GHZ but 2,4 GHZ) and i've checked on the router camera ip - it is "0.20"
hxxp://192.168.0.20/cgi-bin/status is not working as well. I cannot connect using telnet (but of course i've the camera is not hacked - it is somehow obvious, isn't it ? )

What am i doing wrong ? Is this a matter of a new firmware ?

Attaching Printscreens:
1. Two application, that i've downloaded (only this with name in china is working)
![1](https://user-images.githubusercontent.com/21036476/28139832-0e563f4c-6756-11e7-99c8-ce384582569e.jpg)
2. Information about SD cards
![2](https://user-images.githubusercontent.com/21036476/28139842-15563e3c-6756-11e7-8e22-2dbbdd1db35c.jpg)
3. Information about SD card details
![3](https://user-images.githubusercontent.com/21036476/28139849-1b1e08c2-6756-11e7-8602-a09756491582.jpg)
4. Information before running Win32 Disk Imager
![win32_disk_imager](https://user-images.githubusercontent.com/21036476/28139864-29ad65a4-6756-11e7-8e7f-a3b00d63bf57.png)
5. Information after clicking Verify only (before saving image)
![verification_failed_begining](https://user-images.githubusercontent.com/21036476/28139870-2e6ec6be-6756-11e7-9358-48b3a1a996cf.png)
6 Informationa after clicking Verify only (after saving image)
![verification_failed](https://user-images.githubusercontent.com/21036476/28139879-35fa6b9a-6756-11e7-8435-0681c04d6ddd.png)
7. Two partition after image saved to sd card
![two_partition](https://user-images.githubusercontent.com/21036476/28141603-9e8dbf7a-675d-11e7-827e-054977d928ff.png)
8. Main partition
![main_drive](https://user-images.githubusercontent.com/21036476/28141611-a66102a2-675d-11e7-8793-d95948df2dc2.png)
9. Two partition after imaged saved to sd card ("Ext2 File System Driver for Windows" installed)
![two_partition_after_ext2](https://user-images.githubusercontent.com/21036476/28141646-d3b9d4b8-675d-11e7-8311-da4c4f49c056.png)
10. Second (data) partition after "Ext2 File System Driver for Windows" installed
![data_drive_after_ext2_install](https://user-images.githubusercontent.com/21036476/28141662-e537dbe0-675d-11e7-939c-71209991845d.png)

**Comment by Verbank** [comment]
great info thank you

**Comment by samtap** [comment]
Xiaomi MiJia is a different device! This project is about the Xiaomi XiaoFang camera. I don't have a MiJia so no idea if it even uses similar hardware. Would be interesting to find out, if it's similar to XiaoFang maybe we can support it.

**Comment by Filipowicz251** [comment]
Yeah, i've just noticed it is a different device :/ Samtap - how can i assist you with "finding out" if it is similar ?

**Comment by samtap** [comment]
First thing would be find out which hardware it uses. If it is similar to XiaoFang there's a SNX98600 SoC and maybe the software is compatible. But most likely it uses completely different hardware. You could take it apart and take pictures of all the chips etc, see if you can find serial console access and take it from there.

**Comment by theDoc5655** [comment]
i have a mijia too, and i want so hard to get RTSP video out of it.

**Comment by Filipowicz251** [comment]
samtap - i would love to help - but i'm no "hardware" man (more software like to be honest) If there is no screw and i cannot use screwdriver - i'm doomed :) And this is the case (there are no screws in this camera and i don't know how to dismantle it)

Maybe there is someone else with Mijia 1080P camera (beware - they have also Mijia 360 camera and Mijoa car DVR camera - this thread is about "pure" 1080P Smart camera IP)  with proper skills to dismantle it ? Me and theDoc5655 will be most welcome. :)

And really, samtap (and maybe someone who can help us with our camera) - consider some crowdfunding/patronate or plain donation portal - there will be many, who will want to reward you for your good work! ;)

**Comment by theDoc5655** [comment]
don't let die this thread pls :vanuatu:

**Comment by samtap** [comment]
I'll leave the thread open, I don't have a Mijia cam but maybe somebody else can contribute

**Comment by theDoc5655** [comment]
I've some Mijia atm but same problem of Filipowicz251 here

**Comment by icyleaf** [comment]
@Filipowicz251 

Mijia camera is also made by XiaoYi camera, maybe it helps for you:

https://github.com/fritz-smh/yi-hack
https://github.com/niclet/xiaomi_hack

**Comment by Deteorek** [comment]
Hi,
I found this, http://www.hkvstar.com/product-news/tear-down-xiaomi-mijia-360-1080p-pan-tilt-ip-camera.html . I hope it will help a little.

**Comment by theDoc5655** [comment]
if this can help to make a custom firmware for the mijia 1080p standard i'll build you a statue!

**Comment by Filipowicz251** [comment]
But this is for mijia 360 1080p. It is not the same as just mijia 1080p. I suppose the hardware is different - so the hack would be also different :/

**Comment by niighthawk** [comment]
I also want a hack for the sxj01zm ( Mijia 1080p ) to get acces to RTSP

**Comment by ferdydek** [comment]
![img_20170804_173409](https://user-images.githubusercontent.com/5775168/28977985-21db9f2e-793c-11e7-9192-afaa3080659a.jpg)
![img_20170804_173400](https://user-images.githubusercontent.com/5775168/28977984-21da7f36-793c-11e7-9df7-16f10d9b42ef.jpg)
![img_20170804_173354](https://user-images.githubusercontent.com/5775168/28977986-21ddf6a2-793c-11e7-8b24-1e783156391f.jpg)
![img_20170804_173352](https://user-images.githubusercontent.com/5775168/28977987-21dfcd92-793c-11e7-80ec-53e36b38bc50.jpg)
![img_20170804_173330](https://user-images.githubusercontent.com/5775168/28977988-21e1add8-793c-11e7-87b0-92e545d5f967.jpg)
![img_20170804_173304](https://user-images.githubusercontent.com/5775168/28977989-21e2bcb4-793c-11e7-8f0e-157b755ffd2f.jpg)
![img_20170804_173303](https://user-images.githubusercontent.com/5775168/28977990-21f33350-793c-11e7-8125-8cb714078878.jpg)
![img_20170804_172951](https://user-images.githubusercontent.com/5775168/28977991-21f41e28-793c-11e7-9021-a3dc0ab37214.jpg)

let me know if you need more hardware pics.

**Comment by Filipowicz251** [comment]
@samtap what are chances, that you could make use of it and create Mijia Xack ?:)

**Comment by samtap** [comment]
Chances are slim since it's not the same SNX chip as in the Xiao Fang, but this one: http://www.grain-media.com/html/8136S_8135S.htm. So the software is completely different :(

Xiaomi sure is busy putting new cheap cameras on the market lately:
https://www.gizmochina.com/2017/08/03/xiaomi-launches-new-1080p-ptz-smart-camera-%C2%A5149-22/
https://www.gizmochina.com/2017/08/03/xiaomi-releases-new-infrared-camera-motion-detector/

**Comment by snoerenberg** [comment]
@Filipowicz251 is there any firmware available to download? So that it can be analyzed?
I think @samtap was able to find the "autorun" possibility while he was on the serial console.

If there is no possibility to get into console, it would be needed to extract firmware and see if there is any chance to easily start scripts (maybe with root priviledges).

**Comment by Filipowicz251** [comment]
@snoerenberg  - nothing that I'm aware of. firmware is being downloaded automatically by the application. I didn't see any url with firmware to download :/

**Comment by snoerenberg** [comment]
@Filipowicz251 I triggered the FW download in the Mi app and captured on my router (Fritz.Box) the internet connection. So I was able to see the HTTP calls which have been issued by the webcam. Than I downloaded the FW on my PC after analyzing the packets with wireshark.

**Comment by Filipowicz251** [comment]
@snoerenberg  - so you have the firmware? great news :) Maybe post it here - so, that anyone (who knows how to do it:) ) can "try" to find hack?

**Comment by snoerenberg** [comment]
@Filipowicz251 no from the Xiaofang I could capture the FW download. I ordered now a Mijia as well... will take some time to Germany.

**Comment by niighthawk** [comment]
Good

**Comment by niighthawk** [comment]
We should start a new project only for the mijia 1080p camera.

**Comment by snoerenberg** [comment]
@niighthawk we'll see if there is any easy entry point to create a hack.

What is urgently needed? Rtsp? The camera should work outside China with Mi app or?

**Comment by niighthawk** [comment]
I think everyone want it's a RTSP and put cloud system off like others hack, also an option to put the blue light off and also the night mode off.

**Comment by theDoc5655** [comment]
I urgently need the support to RTSP, thanks guys :D

**Comment by andreq** [comment]
Just want to chime in that I'll receive a Mijia in a month or so and will do my best to help here. Meanwhile, was there any github project created for Mijia camera specificaly?

**Comment by snoerenberg** [comment]
Hi,
when you google for "GM8136 SDK release v1.0.rar" you can find some useful stuff.
I dig deeper into this once the camera is delivered.

Can someone in the meanwhile make a port scan on the Mijia?
Thanks

Links:
- SDK http://pan.baidu.com/share/link?uk=2553453276&shareid=3324610145
- Bootloader? http://pan.baidu.com/share/link?shareid=1783156365&uk=2553453276&fid=275039869366609

Stephan

**Comment by snoerenberg** [comment]
Within the SDK is a compiled "rtspd" at least.
\GM8136 SDK release v1.0\Software\Embedded_Linux\image\GM8136_2MP.NAND.jffs2.img -> "rtspd"

**Comment by Filipowicz251** [comment]
Hi

I've created github project for hacks for Mijia 1080p. 

https://github.com/Filipowicz251/mijia-1080P-hacks

I've created also a topic for this:
https://github.com/Filipowicz251/mijia-1080P-hacks/issues/1

**Comment by snoerenberg** [comment]
@ferdydek can you try to find the UART (if there is any)?
I've not got my Mijia device yet.
I've a CP2101 USB-UART Adapter for testing this later on.

Maybe you can check it as well, following a nice summary how to find the right pins (hopefully).
http://www.devttys0.com/2012/11/reverse-engineering-serial-ports/

From my point of view, suspects could be the following:
![board](https://user-images.githubusercontent.com/4847454/29248304-0d9afba6-8015-11e7-858e-ebcb04b6d029.jpg)

**Comment by snoerenberg** [comment]
Hi,
most promising look thos two points. Can someone attach a USB-UART Adapter there?
Try RX/TX and vica versa,

![unbenannt-5](https://user-images.githubusercontent.com/4847454/29252736-03d4f556-806d-11e7-8499-daf4ba4826ac.jpg)

When you look at the traces they go straight to the CPU legs.
The others look like grounded pads.
It's just what I could see from @ferdydek pictures he took.

Thanks
Stephan

**Comment by tobbegutt** [comment]
thank you all guys. ill follow this with great optimism.

**Comment by andreq** [comment]
@snoerenberg, good find! I'm 99% sure the UART is the top most 2 test point on your 2nd photo. They seem to be attached to pin 86 and 87 on the chip, which are UART0_SIN and UART0_SOUT.

If I'm not mistaken, the left test point would be IN and right one would be OUT.

**Comment by kollaesch** [comment]
I don't know if this is any news for you, but on on the SD-Card (for saving videos) there are logs saved from camera as well. (linux kernel log)
Let me know if you could use them for checking as well.

**Comment by snoerenberg** [comment]
@kollaesch would be nice. Mine is still in transit. No one with an USB-UART Adapter here to check if a writable root shell is present? :)

Thanks

**Comment by willthrom** [comment]
Mine is in transit as well. As soon as it arrives I will give it a go.

**Comment by kollaesch** [comment]
@snoerenberg I have an USB-TTL at home. 
How to connect? I couldn't open the cam myself yet. What's the trick? (howto somewhere?)
The log follows this evening.

**Comment by kollaesch** [comment]
@ferdydek How did you open the cam?
(with or without breaking the snapin-hooks)

**Comment by kollaesch** [comment]
the logs from the boot of the cam are listed here:
[pastebin](https://pastebin.com/raw/53hdb4x0)

**Comment by snoerenberg** [comment]
Log looks good:

Jan  1 08:00:02 kernel: [    0.000000] Kernel command line: mem=128M gmmem=90M console=ttyS0,115200 user_debug=31 init=/squashfs_init root=/dev/mtdblock2 rootfstype=squashfs

So a console should be present on UART.

Seems also that the encrypted Miot traffic is dumped to this log. 👍

**Comment by ferdydek** [comment]
@kollaesch simple plastic priming tool, wasn't difficult at all. It left super small wite trace in one place. No biggy.
There was a lose 1cm shrink tube inside (fun fact).

**Comment by ferdydek** [comment]
@snoerenberg it may take me a while, my multimeter burned waiting for new one to arrive.

**Comment by samtap** [comment]
I've pre-ordered one of these: http://www.gearbest.com/ip-cameras/pp_693217.html
Think there's a good change hardware is the same as in Xiao Fang...

**Comment by andreq** [comment]
@samtap this "issue" is focusing on the mijia 1080P, you'll have better chance to create a new one for this specific camera.

Side note, should we all move over to https://github.com/Filipowicz251/mijia-1080P-hacks for further chat about the Mijia?

**Comment by kollaesch** [comment]
@ferdydek I got it open. The plastic tube is the cover for the long led-glas-tube. Put it over/around again :)

**Comment by snoerenberg** [comment]
@kollaesch maybe you can make a picture how to open it or point out where the clips are.

Thank you

**Comment by kollaesch** [comment]
So, guys - thanks for all the previous hints! - I can confirm ... It's alive ;) 

_Referring to the picture last picture in snoerenberg's post_
The top right connection points are responding to: TX,RX (in that order from left to right)

pictures and boot-uart-log follow.

**Comment by kollaesch** [comment]
I'm switching to "Filipowicz251/mijia-1080P-hacks" right now. Follow us/me there.

**Comment by willthrom** [comment]
@Filipowicz251 close this issue so we don't carry on this discussion here :)

**Comment by Filipowicz251** [comment]
You are right :) I'm closing it.
