### ISSUE TITLE
Flip image?

### ISSUE THREAD

**Issue by snailium** [samtap/fang-hacks#191]
Hi,

I'm planning to celling mount one of my Fang's. Is there any easy way to flip the RTSP image?

Thanks.

**Comment by samtap** [comment]
Yes snx_isp_ctl can do that, there's just no user-friendly (web-interface) method to configure it. So you have to edit i.e. the rtsp server script to add it.

**Comment by snailium** [comment]
OK, found solution in Issue #78.

Any plan to create a configuration page for image control?

**Comment by samtap** [comment]
Yes lots of plans ;-).
