### ISSUE TITLE
Rotate RTSP stream

### ISSUE THREAD

**Issue by gokuu** [samtap/fang-hacks#198]
Hello!

Is it possible to rotate the RTSP stream by 180º? I had to mount the camera upside down, and would like to rotate the stream, if possible, before it actually leaves the camera.

**Comment by LouiS22** [comment]
Hello there,

Just follow Bobby Romero's guide [http://bobbyromeo.com/technology/xiaomi-smart-1080p-wifi-ip-camera-rtsp-streaming-hack/](url), and you'll get there.

You need the "Install snx_isp_ctl" section, and "Flip/Mirror Image" section. It's like a 2 minutes job, did it yesterday myself the same.

**Comment by gokuu** [comment]
Perfect, thanks!

**Comment by kszere** [comment]
Link not available.

**Comment by Bechrissed** [comment]
He (Bobby Romero) modified urls, the article is still there. Now to found under the following link: http://bobbyromeo.com/home-automation/xiaomi-smart-1080p-wifi-ip-camera-rtsp-streaming-hack/
