### ISSUE TITLE
Stuck on 404

### ISSUE THREAD

**Issue by tobilap** [samtap/fang-hacks#2]
I got really exited once i saw your project after reading the discussion on the other github repo(yi-hack).
I'v setup everything the way you mentioned it in your readme.
100mb on /dev/sdd1  using mkfs.vfat
rest of the 16gb on /dev/sdd1 using mkfs.ext2

After inserting the SD card in the booted camera it does make a sound after a few seconds so I guess the runscript got executed (as I read in the yi-hack repo)

Sadly I'm getting a 404

The Camera is running on 2.8.3.5

**Comment by samtap** [comment]
Can you use telnet to login? If so, please check the contents of /tmp/hacks.log

**Comment by tobilap** [comment]
Sadly no, I did a portscan using nmap and telnet is closed. I just started preparing another sd card, maybe this will help.

**Comment by samtap** [comment]
If you go to hello.cgi you should see a directory listing of the vfat partition, or opendir failed message is the sdcard isn't mounted

**Comment by tobilap** [comment]
hmm, getting a 404 as well.

**Comment by samtap** [comment]
Sure you're using the correct url? http://device/cgi-bin/hello.cgi

**Comment by tobilap** [comment]
Arg. Was the SD card....works fine with the 3rd one i have set up...
Thanks for the help :)

**Comment by dvbit** [comment]
might be interesting: 
rebooted
at first try I got connection refused
then 404
