### ISSUE TITLE
What is Xiaofang UART Driver?

### ISSUE THREAD

**Issue by thanhson1085** [samtap/fang-hacks#210]
I want to connect my OSX to Xiaofang Camera via serial port. What UART Driver should I install to connect the camera?

**Comment by samtap** [comment]
I'm not familiar with OSX but I imagine you're talking about usb driver for the serial rs232-to-usb adapter? I.e. a FTDI or ProLific (PL) chip. That depends on the adapter you're using, it's not part of the camera.

If you have a choice pick an ftdi adapter, they're a bit more expensive but worth the extra buck.

**Comment by thanhson1085** [comment]
Yep, I understood. Do you have any tutorial to connect Serial on Xiaofang from Computer?
