### ISSUE TITLE
how can i access the camera via 4G?

### ISSUE THREAD

**Issue by psycholaser** [samtap/fang-hacks#211]
hey guys, 
hack works good and i managed to access the camera and view from tinycam app but only when connected to the same wifi as the cam!

is it possible to make it work so i can access it from any internet connection?? after all that the purpose of it hehe so i can watch it when im outside.

thanks!

**Comment by samtap** [comment]
You need to forward a port in your router (not really secure) or use some form of vpn (secure if done correctly). As this is a general networking question and not an issue with the camera, I'm closing this. Feel free to join discord chat if you need help.
