### ISSUE TITLE
rstp-server issue

### ISSUE THREAD

**Issue by lybrian** [samtap/fang-hacks#217]
I have to restart my 20-rtsp-server keeps saying NOK and I need to stop & start the service on a daily basis

**Comment by halfluck** [comment]
Hey Mate,

add the RTSP Check Service to your Fanghack and it will restart RTSP Service if it falls over

There is a guide on it here ==> http://bobbyromeo.com/technology/xiaomi-smart-1080p-wifi-ip-camera-rtsp-streaming-hack/

Cheers Rob.

**Comment by lybrian** [comment]
working. thanks!
