### ISSUE TITLE
Will you good friends, hackers after the camera how to set the screen flip it?

### ISSUE THREAD

**Issue by 1043717432** [samtap/fang-hacks#218]
Will you good friends, hackers after the camera how to set the screen flip it?
I need to hang the camera.

**Comment by Chrischi-** [comment]
https://github.com/samtap/fang-hacks/wiki/Controlling-the-text-overlay

         --mfset-mode                   Set Mirror Flip Mode(mode:off:0, flip:1, mirror:2, flip&mirror:3)

**Comment by 1043717432** [comment]
@Chrischi- Thank you!

**Comment by 1043717432** [comment]
Where is it set up?

**Comment by Chrischi-** [comment]
telnet "ip of cam" 2323

U: root
P: ismart12

camhostname$ ./snx_isp_ctl --mfset-mode 3
Set Mirror Flip Mode(mode:off:0, flip:1, mirror:2, flip&mirror:3)

**Comment by 1043717432** [comment]
@Chrischi-  
Thank you, bother, I failed to log in tenlet login, can tell me how to operate?
![qq 20170908123401](https://user-images.githubusercontent.com/22461690/30196262-e5f18f52-9491-11e7-86b1-9df6437510ad.png)

U: root
P: ismart12

camhostname$ ./snx_isp_ctl --mfset-mode 3
Set Mirror Flip Mode(mode:off:0, flip:1, mirror:2, flip&mirror:3)
