### ISSUE TITLE
">$LOG 2>&1 &"  ?

### ISSUE THREAD

**Issue by StefanMeGit** [samtap/fang-hacks#224]
For what is this in the settings of the RTSP server? Can find any information about it....

Stefan

**Comment by samtap** [comment]
Settings? It's in the startup script to redirect output to a logfile.

**Comment by Mattie112** [comment]
Did you google? As the first I don't know how many links give you the right answer :)

https://www.google.com/search?q=2%3E%261+%26&oq=2%3E%261+%26&aqs=chrome..69i57j69i61j0l4.159j0j7&sourceid=chrome&ie=UTF-8

https://stackoverflow.com/questions/818255/in-the-shell-what-does-21-mean
