### ISSUE TITLE
我删除了/etc/fang_hacks.sh、/etc/fang_hacks.cfg、/etc/fang_hacks.cfg.bak，重启后一直黄灯怎么办?

### ISSUE THREAD

**Issue by LiuJiangshan** [samtap/fang-hacks#228]

**Comment by LiuJiangshan** [comment]
??

**Comment by ykhandler** [comment]
Just flash a genuine firmware or a custom firmware. Look at this video to do it:
https://youtu.be/mpzPWYONWZA

**Comment by SpoKeys** [comment]
Can you share the firmware you have used, or some details about it?

**Comment by ykhandler** [comment]
Of course. I will share it on my youtube. But currently i'm designing the easiest way so every body will understand it.

**Comment by SpoKeys** [comment]
Please try any way you can. Also I see the clip is restricted outside the app(not available on browser) so comments are hard to get. 

Probably there are more people like me that would like to know how to get 0.elf from a .img file that is the default file format for firmware upgrade. I am not really an IDA user but I`ll do whatever it takes.

**Comment by samtap** [comment]
I'm removing this thread. I've no idea what's going on from chinese title to someone trying to lure people to his youtube channel. Please be clear when you open a new issue, if you just have a question or need support drop by gitter chat.

**Comment by ykhandler** [comment]
Peace Samtap. Simple answer: Flash the Firmware to recover your camera LiuJiangshan...
