### ISSUE TITLE
Hack not working

### ISSUE THREAD

**Issue by Devangel67** [samtap/fang-hacks#23]
I write the image using win32 disk imager and boot the device without the sd-card then i insert the sd but nothing work, i get always the same "404" and "OpenDir faile".

I tried everything but nothing work..What are ami doing wrong ?
I use the last firmware.

PS: Sorry for my english.

**Comment by laucho** [comment]
hi 
go the same thing, i put the sd in when the camera is powered.
A sound happened but the url is still 404, i tried it several times powered or not powered.

Thanks

**Comment by laucho** [comment]
Ok it goes on :)
the url is http://YOUR_IP/cgi-bin/status (little mistake on the front page)
but on apply : 
`Applying fang hacks scripts...
Source file not found: '/media/mmcblk0p1/bootstrap/sdcard'
Source file not found: '/media/mmcblk0p1/bootstrap/rc.local'
Source file not found: '/media/mmcblk0p1/bootstrap/rcS'
Source file not found: '/media/mmcblk0p1/bootstrap/fang_hacks.sh'
Source file not found: '/media/mmcblk0p1/bootstrap/fang_hacks.cfg'`

**Comment by Vennerstrand** [comment]
@laucho See my last post in #21. You will need to enable telnet from web, telent, mount sd-card partition p2 and then you can apply the hack.

**Comment by Devangel67** [comment]
I don't have any sound, if i go to http://myip/ the page is empty but i don't get any ''404'' or 'opendir faile'. Well i think my camera is broken...Ahaha

**Comment by Gilgameshismist** [comment]
Devangel67 That is a bit sparse, do you have more information?
What FW are you on? Which modifications have you made? Which versions of hacks are you using? What action have been performed before the camera stopped working? Is there an SD card in the device? If so: what is on the SD card? What is the status of the led? Does the IR sensor click if you cover the front of the camera? What happens if you push the Reset button?

**Comment by Devangel67** [comment]
Well i unplug the camera, plug in and press the setup and everything works again. But the hack don't work, I'm use the latest firmware, no modification , i just used win32 disk imager to write the image on the sd card, so i get a fa32 partition and a ext2 partition and insert the card after the boot but nothing, 

I hear the sensor when i cover the front of the camera and mi home work well. Where is the reset button ?

**Comment by Gilgameshismist** [comment]
The reset button is on the bottom of the camera, you used it to set up the WIFI connection. 
But what I hear now is that the camera works, but the hacks don't apply.
If you let the camera boot and the LED is blue you can connect with mi home, this is good!
Now you can pop in the prepared SD card, it will take a few seconds but you should hear a dingding sound. If not something is wrong with the SD (or the way the camera is mounting the sd).
If you wait some time after inserting the SD you should be able to go to camip/cgi-bin/status , does this load? (you need to be on the same wireless network as your cam to be able to reach that page!)

**Comment by Devangel67** [comment]
I inserted in the camera but no sound, always error 404 but the camera saved pictures on the sd card...I'm gonna try another sd card to see if something change, its a sandisk ultra 16gb.

**Comment by Gilgameshismist** [comment]
If the camera doesn't give the dingding sound after the SD is inserted, it probably doesn't detect it as SD. Either the SD is corrupt, or the image wasn't written to the SD right. (Which I can't help you with, I never used the image file, I made the partitions using gparted)

**Comment by Devangel67** [comment]
This time i have the status page with this : 
README.md
bootstrap
snx_autorun.sh
time_lapse
record

But the status page said 404...Better than before i guess.

**Comment by Gilgameshismist** [comment]
I don't think that is the status page, that looks like the result of hello.cgi
it looks like snx_autorun.sh doesn't run. 
Which version of diskimage are you using? If you have firmware v3.0.x you should use image v0.2.0.

**Comment by Devangel67** [comment]
Sorry, that the hello.cgi page, i used gparted to create a fat32(i am wrong)partition and ext2 and copied the files from github.  The camera save files on the sd card but i don't understand why the snx_autorun doesn't run... 

I tested a bit and the camera doesn't detect the sd when i let the camera boot, only if i insert the sd and plug in the camera... Thank you anyway :).

**Comment by Gilgameshismist** [comment]
Hi @Devangel67, any progress? Did you manage to get it running?
Did you try another SD card?
 Regards,

**Comment by Devangel67** [comment]
I tried some sd cards, same problem...Telnet > refused, 192.168.15.18/cgi-bin/ > 403, 192.168.15.18/cgi-bin/status > 404.

Mi Home detect the sd card and i can save picture or something like that but i don't undersand why the script doesn't run..

Something is wrong with my camera i'm sure but why everything work perfectly in mi home ?...

The only  strange thing in mi home, if i boot with the sd card no problems but if i insert the sd after the boot nothing is detected.

I need a miracle :D

**Comment by tooviral** [comment]
Have you tried different sd cards??

**Comment by Devangel67** [comment]
Of course i tried but same results. I am going to buy another one to see if this one is faulty.

**Comment by samtap** [comment]
To test if mounting works correctly, insert the sdcard AFTER the device has booted. Then go to http://device-ip/cgi-bin/hello.cgi. This is a default script, not part of the hacks, and should list the contents of the vfat partition (including snx_autorun.sh). If you get some error (openDir failed), you may have a corrupt filesystem that prevents it from getting mounted. Try to repair it or use a new card and start from scratch.

**Comment by Devangel67** [comment]
I tried many sd cards, nothing work...When i boot with the sd card i get the hello.cgi but only in this case. What can i do now ?

**Comment by Devangel67** [comment]
Finally the hack work but in the "manage script" the ftpd, rtsp-server, ir-control are "NOK".

**Comment by samtap** [comment]
@Devangel67 Please read through #17 and the [FAQ](https://github.com/samtap/fang-hacks/wiki/F.A.Q.) or maybe you can find some help on discord chat?

**Comment by Devangel67** [comment]
Thank you very much, everything work yet :).

**Comment by iliya2003** [comment]
The same problem, how did you fix the 404 problem??
