### ISSUE TITLE
How to roll back to original state?

### ISSUE THREAD

**Issue by greenlama** [samtap/fang-hacks#24]
How can I clean the cam from this hack?

**Comment by samtap** [comment]
If you remove /etc/fang_hacks.sh and /etc/fang_hacks.cfg, all hacks are disabled. Originals of files that are modified (rc.local, rcS, sdcard) are still in /root but it should not make any difference.

**Comment by minomoto** [comment]
but be careful...   rm /etc/fang* was last action in life of my cam...

**Comment by bookamp** [comment]
Yes - I just did this and my led is stuck on orange. Information seems to be incorrect and will likely brick your camera.
