### ISSUE TITLE
how to build my own RSTP server?

### ISSUE THREAD

**Issue by masterchop** [samtap/fang-hacks#245]
I would like to build my own RSTP server but i have no idea how to compile for this device.
Can i get some help on this thanks

**Comment by samtap** [comment]
What have you tried so far? Do you have the SDK?

**Comment by masterchop** [comment]
i have tried in anotherr IOT device but i always get roadblock as i dont know what i need for that IOT, i do not have the SDK which one it is? Could you please supply more info so i can google a bit more?

**Comment by samtap** [comment]
I wouldn't really know where to start ;-). I'll close this since it's not really an issue but feel free to join us on gitter to chat about homebrew IoT / cameras (https://gitter.im/fang-hacks).
