### ISSUE TITLE
Auto reboot

### ISSUE THREAD

**Issue by martyouel** [samtap/fang-hacks#249]
Hello,

I have my xiaomi cam since yesterday and as soon as I received it I installed fanhacks.
I did some test during 1 day...rtsp enabled...everything's was ok.

I moved the cam today to its "good  place" but since this, the cam run 30 seconds, and then, reboot automaticaly. I am not able to make it stable.

Here's was I did ->

- Plug in the cam with no card
- When the light is flashing blue, insert the cam
- I heard a sound from the cam
- Go to http://192.168.12.XXX/cgi-bin/status...from there ensure that telnet is running
- Connect in telnet on the cam...kill 2 ICamera process
- Go again on http://192.168.12.XXX/cgi-bin, in scripts, and start rtsp_server
- Try to connect rtsp...works
- 30 seconds later, I head a "click sound" on the cam...rtsp "turn off"...so the cam rebooted.

What's wrong guys ?
I love the video quality of this cam but I would like to get some stability :)

thanks

**Comment by samtap** [comment]
The camera is restarted if you don't unload snx_wdt (watchdog timer). I don't know why you would login and kill iCamera manually? The stop-cloud script does that automatically, if you boot with the sdcard inserted. Once the hack is applied you need to leave the card inserted, if you remove the card it reverts to normal behavior.
