### ISSUE TITLE
Combining 2 cameras together

### ISSUE THREAD

**Issue by chakal** [samtap/fang-hacks#25]
Has anyone tried combining 2 camera together to create a wider video stream like the Cloud app does? I still haven't received my cameras yet but this is a feature that would be interesting to have. I assume that connecting a camera to another via USB adds a video device, but I cannot confirm that...

**Comment by samtap** [comment]
Nope the usb port supplies power only. It is mentioned in one of the reviews out there that it's just a software feature that stitches the image together to appear as one stream.
