### ISSUE TITLE
404 and no files on /media/mmcblk0p1

### ISSUE THREAD

**Issue by fdgago** [samtap/fang-hacks#250]
Hi.
Hi have problems with the first step. I receive the 404 error and on the helllo.bin I receive an empty page.

I have activated the telnet lines on the autorun script and I have accessed via telnet to the camera.This implies that the script has been executed.
The log file hacks.log seem to be correct.

The problem I have is that I don't have any files on the /media/mmcblk0p1 and mmcblk0p2 directory's. The ls command is empty.

What can be the problem?
I have created the image of the sd-card using Win32 Disk Imager.
Thanks

**Comment by samtap** [comment]
Post firmware version and output of 'mount' command

**Comment by fdgago** [comment]
The problem can be due a special kind of error in the Microsd or incompatibility.
I have changed the Microsd and it works.
Thanks for your support.
