### ISSUE TITLE
Request remote recording on a PI

### ISSUE THREAD

**Issue by dendrees** [samtap/fang-hacks#262]
Does somebody have an easy tutorial to setup remote recording on a PI with these little ip camera's?
I mean capturing the RTSP stream on a PI over wifi?

**Comment by zhernovskyi** [comment]
ffmpeg -y -i rtsp://you_came_ip:554/unicast -c copy -map 0 -f segment -segment_time 300 -segment_format mp4 "capture-%03d.mp4"

**Comment by samtap** [comment]
Closing, answered.
