### ISSUE TITLE
Xiaofang Timelapse Error

### ISSUE THREAD

**Issue by lawrnz** [samtap/fang-hacks#264]
Hi Everyone,

I'm the new guy here. Be good to me. lol.

I recently bought the Xiaofang Ip Cam. The small square one to be precise. I tried experimenting on the camera and tried fang hack. Thanks by the way. I'm currently having issue using its timelapse mode. I'm not sure if it's just my camera but seeing youtube videos using their camera for timelapse it should actually work. I tried updating the firmware to the latest version 3.2.0.30. But that didn't help. Downgraded it back to 3.0.3.56 but to no help.

The issue I was having was when I click on the timelapse option it just goes black. I tried waiting for a couple of minutes but nothing happens. It was as if the app was hanging or something. Current MiHome App version by the way was 5.0.10 if that helps.

P.S.
It's not that the timelapse option was important for me but might come in handy when needed. And since that feature is included in the app/camera, it's a waste if I won't be able to use it.

Thanks ahead.

**Comment by samtap** [comment]
For Mi Home support please post your questions on Xiaomi forums
