### ISSUE TITLE
Error: Nothing is mounted...

### ISSUE THREAD

**Issue by wartaf** [samtap/fang-hacks#266]
i just hack my device with 34:xx Mac ID. then after the installation and extending the partition. it says 'Script is already installed! Error: Nothing is mounted on /media/mmcblk0p2!' then i tried the manual mount. it says 'Mounting /dev/mmcblk0p2 to /media/mmcblk0p2...
Device is present (filesystem: ext2)
mount: mounting /dev/mmcblk0p2 on /media/mmcblk0p2 failed: Device or resource busy 
Failed to mount!'. then i click the manage scripts but only the top 4 buttons are there. no table of rtsp or ftp. etc.... 
i tried to reboot it.. unplug the power..  but nothing changed.. 
here's the only thing written on log

Contents of /tmp/hacks.log:
resize2fs 1.43.3 (04-Sep-2016)

i wonder if its a bug or i did something wrong.. thanks in advance..

edit: btw the mi home apps still working and recording. 

edit: looks like the resize2fs still running.. thanks..

**Comment by Tusenka** [comment]
there is a different devices name could be
