### ISSUE TITLE
securing the video stream

### ISSUE THREAD

**Issue by conradhagemans** [samtap/fang-hacks#27]
I was wondering if it's possible to secure the video stream with a username/password?

I would like to see the video stream from outsite my network. So I open the port in my gateway.
But in that case the whole world can have access to my camera to see the stream.

Does anyone know how to make it secure?

**Comment by samtap** [comment]
You could use an ssh tunnel. There's also some work in progress to build a new rtsp server with authentication support. Please use #6 for more comments.
