### ISSUE TITLE
I do not know what to do with the Fang-Hacks

### ISSUE THREAD

**Issue by STijeras91** [samtap/fang-hacks#276]
Hello everyone! I had a Xiaofang camera that could only be used in China, I made it downgrade to 3.0.3.56 and I loaded the hacks, I can access it by rtsp, telnet, ftp ... etc.
Now I want to use the Mi Home application or something similar that allows me to see the camera from outside the house, I use IOS. There's a possibility?

Thank you so much

**Comment by samtap** [comment]
Sure use a RTSP client for IOS and a vpn to secure access. This has been discussed many times before and on other websites. Good luck, if you run into issues you can ask on gitter or wait for a next release that may be a bit more user friendly.
