### ISSUE TITLE
Downgrade from firmware 3.3.3.25

### ISSUE THREAD

**Issue by joker462** [samtap/fang-hacks#286]
I've updated firmware 3.3.3.25 so that device cannot read and write microSD card anymore. Please suggest me anyway to restore old firmware can uses microSD card.

**Comment by samtap** [comment]
https://github.com/samtap/fang-hacks/wiki/HowTo:-Flash-original-Xiaomi-firmware-from-sdcard-(factory-reset)

**Comment by joker462** [comment]
Hi samtap, the orange LED of the device cannot be flashing anymore. I've powered up the device again but it only has orange LED and wait for 10 minutes but it cannot be flashing.
