### ISSUE TITLE
Can't connect to access point that has space in its name in Wireless Client Mode

### ISSUE THREAD

**Issue by andrew-yu** [samtap/fang-hacks#287]
![issue](https://user-images.githubusercontent.com/27214373/34253990-fdc8d0ac-e65a-11e7-925a-402e1c4c7e38.jpg)

In this case access point properties looks like
Name:<name of access point before space>
Address:<name of acces point after space>
Signal:WPA%
Security:<access point MAC>

After clicking on the Connect button, a message appears Security:<access point MAC>  is not supported

**Comment by samtap** [comment]
Yeah that's already known, the fix is simple but you have to update some files on the sdcard. You can also just manually edit wpa_supplicant.conf on the sdcard.
