### ISSUE TITLE
Scripts randomnly stopped working on 2 cameras at same time.

### ISSUE THREAD

**Issue by catscandrive** [samtap/fang-hacks#288]
https://imgur.com/a/gpoVV

I can manually start all except the rtsp script.  It tells me dev/video0 doesn't exist.  I think my next step would be to reset the cameras and try again, but are these in any way stable ever?  Mine haven't worked reliably in the week I've had them.

**Comment by samtap** [comment]
Do they get hot? Some of my cams have run for months and generally RTSP only goes down when I need to unplug it to use a different power socket..

**Comment by catscandrive** [comment]
something called iCamera running and hogging /dev/video0?  I'll see how it goes, otherwise i'll just write a script to kill it on boot.

**Comment by samtap** [comment]
That script already exists and should run on boot (unless you disabled it). Also how can iCamera claim it, you said it 'doesn't exist' which is something completely different. Please be clear when reporting an issue.
