### ISSUE TITLE
Timezone is mixed up

### ISSUE THREAD

**Issue by conradhagemans** [samtap/fang-hacks#29]
I life in The Netherlands. That is GMT +2.
If I fill in on the status page GMT -1 I get the correct time.

**Comment by samtap** [comment]
Please see [FAQ](https://github.com/samtap/fang-hacks/wiki/F.A.Q.#the-timezone-is-incorrect)

**Comment by conradhagemans** [comment]
Sorry. You are right. Amsterdam is CES -1:00

Now it 100% correct.

Thanks
