### ISSUE TITLE
Disabling http server, possible ?

### ISSUE THREAD

**Issue by nmaster2042** [samtap/fang-hacks#291]
Hi,

I'm looking for a way to disable the http server to avoid someone else modify the cam parameters.

I looked at the /etc/init.d folder but I can't find the init script of the http server (boa if I undersand).

What I want is to disable it, and be able to enable it again if needed.

Thank you for help.

**Comment by dasmoover** [comment]
netstat -tunap | grep httpportgoeshere

this will show you the name of the process and you can use killall PIDhere to kill it.

**Comment by samtap** [comment]
The webserver process is called boa. If you use iCamera (the cloud app), it is started automatically and you have to kill it like @dasmoover suggested (not sure if some iCamera or Mi Home feature depends on it).

If cloud is disabled, boa is started by the fang-hacks [script](https://github.com/samtap/fang-hacks/blob/master/bootstrap/fang_hacks.sh#L108) so you could just comment or remove that line to disable it.

**Comment by nmaster2042** [comment]
Hi, thank you, I'll try this.
