### ISSUE TITLE
How to format in vfat???

### ISSUE THREAD

**Issue by claudioita** [samtap/fang-hacks#30]
How to do as per instructions? Any tool for windows machine? Instead of VFAT can I use FAT32?

1. Prepare an sd-card with two partitions.

The first partition on the device must be a vfat partition. It will only contain some small scripts so 100MiB should be more than enough. The second partition must be an ext2 partition and will contain all other files.

**Comment by TylonHH** [comment]
So, is it FAT32?

**Comment by taitems** [comment]
I'd also love some instructions on how to do this, specifically on MacOS?
