### ISSUE TITLE
Xiaofang MAC 5C:FF:FF..., Is this camera was delivered with a hack?

### ISSUE THREAD

**Issue by leonidas2522** [samtap/fang-hacks#307]
I have 2 new Xiaofang cameras.
I use Ip Scanner to find MAC address.
One was detected MAC 5C:FF:FF...., which belongs to Shenzhen Kezhonglong Optoelectronic.
But the label at downside of the camera is the MAC 34:CE:00...., which is XIAOMI.
This camera works fine with Mi Home app. Firmware is 3.0.3.56.

Is this camera was delivered with a hack?

**Comment by ril3y** [comment]
No.  Most likely a different batch of wifi adapters installed in each
camera.

**Comment by leonidas2522** [comment]
Thanks you, ril3y. :)
 I just read this topic and suspect. 
https://github.com/samtap/fang-hacks/issues/65
