### ISSUE TITLE
Support for cifs mount

### ISSUE THREAD

**Issue by vaidyasr** [samtap/fang-hacks#312]
I was trying to mount my samba/cifs share and I am getting 'No such device' error. I found there is no cifs kernel module enabled, is there a way to build it?

**Comment by vaidyasr** [comment]
Finally I have created a cifs.ko module to mount samba/cifs shares. Now I can either write the video directly to the NAS or move the contents of video periodically.

**Comment by mouth4war** [comment]
That's great. Could you share?

**Comment by vaidyasr** [comment]
Link: https://sourceforge.net/projects/nmtcsi/files/cifs_mount.zip

**Comment by vaidyasr** [comment]
Insert slow-work.ko first and then cifs.ko
```
# insmod slow-work.ko
# insmod cifs.ko
```

**Comment by samtap** [comment]
@vaidyasr Nice work, could you give some instructions how you built the module so people can repeat it and perhaps build other modules as well?

**Comment by vaidyasr** [comment]
Under the kernel config, I modified'CONFIG_CIFS=m' and did setup variables ARCH and CROSS_COMPILER manually.
Ran make M=fs/cifs under src directory of kernel and I got the cifs.ko. After doing insmod, I found un-resolved symbols, so I did built slow-work too which fixed the issue.

If anyone have any doubts, please let me know.

**Comment by redpig888** [comment]
Will you try to mount samba4 share directory? I can't mount it successfully. Get "Permission denied".  And CIFS VFS: Send error in SessSetup = -13.
Thank a lot!
