### ISSUE TITLE
Few binaries for Xiaofang

### ISSUE THREAD

**Issue by vaidyasr** [samtap/fang-hacks#314]
I have cross compiled busybox with all possible commands, interested can download from:
https://sourceforge.net/projects/nmtcsi/files/busybox_xiaofang.zip

**Comment by gotttlieb** [comment]
Please refer to the source code and the way you do it. 
Trusting a ZIP without knowing the source code and the way it has been done  is foolish.

**Comment by vaidyasr** [comment]
I have selected almost all options in the 'make menuconfig' and posting the .config may not be a good idea as it is very big. I have been doing cross compiling for the past 9+ years for mips and arm platform.

**Comment by vaidyasr** [comment]
Rsync: https://sourceforge.net/projects/nmtcsi/files/rsync_xiaofang.zip
Cifs mount: https://sourceforge.net/projects/nmtcsi/files/cifs_mount.zip
LFTP: https://sourceforge.net/projects/nmtcsi/files/lftp_xiaofang.zip

**Comment by mouth4war** [comment]
@vaidyasr Do we need to update busybox to use cifs/rsync?

**Comment by vaidyasr** [comment]
@mouth4war Not required, the busybox contains missing applets/commands which was not there in the original.

**Comment by mouth4war** [comment]
Can't get cifs to work. Syslog shows invalid username errors. Oh well.

**Comment by vaidyasr** [comment]
The correct syntax for cifs mount is
mount //192.168.1.1/disk1 /media/mnt -t cifs -o username=xyz,password=xyz

**Comment by mouth4war** [comment]
@vaidyasr mount: mounting \\192.168.31.1\下载 on /media/mnt failed: No such device

**Comment by mouth4war** [comment]
OK got it to work! Need to insmod after every reboot and I didn't know that. Sheesh.

Sidenote: doesn't seem to work with those chinese characters.

**Comment by ivanfor** [comment]
Hi @vaidyasr , could you upload your busybox version agail? It's not available anymore.
Thanks in advance
