### ISSUE TITLE
Save video files to sd card

### ISSUE THREAD

**Issue by psmanek** [samtap/fang-hacks#33]
Hi, camera only stream video, but does not save it do sd card. Any ideas?

**Comment by samtap** [comment]
It's fairly easy to modify the rtsp server code and save all frames to a file. The difficulty is in making it configurable, i.e. enable/disable it on the fly, split files, circular buffer, record on motion detection etc.

The first step is merging the snx rtsp server with the latest rtsp server codebase, then we can start on adding features. The current rtsp server is a hack and I don't want to waste time on improving it...

**Comment by psmanek** [comment]
ok, so 512MB sd card is more then enough :)
