### ISSUE TITLE
fang hack not working, how to check what firmware do I have ?

### ISSUE THREAD

**Issue by L3M4R** [samtap/fang-hacks#335]
Hi

I have Chinesse version of xiaofang and not sure did I downgraded firmware correctly, because I can't access status page ("404 Not Found The requested URL /cgi-bin/status was not found on this server".), hello.cgi ("OpenDir faile"). Camera is connecting to my router and is visible on MI Home but "only used in mainland China" :-(. This is newer camera without setup hole.

How to check firmware camera version ?

**Comment by L3M4R** [comment]
Finally working, after third memory card :-).

**Comment by xescaich** [comment]
Hi, how did you do this??

**Comment by minomoto** [comment]
Did you use password ismart12? @L3M4R
