### ISSUE TITLE
Which camera to buy

### ISSUE THREAD

**Issue by radokristof** [samtap/fang-hacks#337]
Dear Everyone!

I have been reading through the issues here and I'm a little bit lost now. I want to buy some of these cameras to use it for indoor surveillance. I don't need any of these cloud-based things, I just only need to get RTSP stream from the camera (and if possible controlling the IR and other stuff through any kind of requests), because I will integrate it to my smarthome system.

The only problem is:

- I haven't found anywhere on the internet Xiaofang cam which is EU version. All of them marked as non-EU or says nothing about the region, so I think that these are also chinese version. (If anyone can provide a link where I can buy EU version I will be happy.)

- I have read that Wyzecam can be also used and hacked, but I still can't find anywhere to buy this camera. (I live in the EU)

Can anyone help me selecting the camera which I will have the biggest chance to install this hack?

Thanks for everyone!

**Comment by 12nick12** [comment]
I purchased this https://5link.cc/JSKEX and I just opened one today and got it working
