### ISSUE TITLE
Unable to put the user and password while downgrading

### ISSUE THREAD

**Issue by xescaich** [samtap/fang-hacks#340]
Hi, I've been trying to downgrade the xiaomi xiaofang 1080p.
I've tried with this tutorial: https://github.com/samtap/fang-hacks/wiki/HowTo:-Flash-original-Xiaomi-firmware-from-sdcard-(factory-reset)#via-ssh--serial

I've tried the 2 methods, sd and with putty.
The problem that I have with putty that I can not insert the user and password, it goes to fast and when i put the user: root it has automatically skip and gone to the other line.
Someone could please help me please???
Thanks
this is what happens me: <a href="https://imgbb.com/"><img src="https://image.ibb.co/fdV997/Sin_t_tulo.png" alt="Sin_t_tulo" border="0"></a>

Thanks

**Comment by minomoto** [comment]
ESC?

**Comment by xescaich** [comment]
i've tried with esc key and also nothing @minomoto

**Comment by xescaich** [comment]
@astraforce I've seen that you have done it, what i have to do'?? THanks

**Comment by xescaich** [comment]
I resolve it, and its working.
i close the issue
