### ISSUE TITLE
Timezone wrong on recorded folder structure

### ISSUE THREAD

**Issue by admisi** [samtap/fang-hacks#35]
I've set up the camera with a 128GB SD card using a large FAT32 partition and the MiHome app to record continuously and save to SD, and then activating ftpd so that I can access the recordings - works perfectly.

However, Timezone adjustments work great for displaying timestamps on the live video and recorded video, but if recording continuously using the MiHome app onto the sd card, 1 minute mp4 files are saved in /media/mmcblk0p1/record/  but the folder structure is saved still in Chinese time.

Any way to change the way the camera creates the folder structure so that it is in local time?

**Comment by samtap** [comment]
So, go complain to Xiaomi. Obviously this is beyond my control I don't create the cloud app!
