### ISSUE TITLE
Is there a way to run scripts when motion is detected?

### ISSUE THREAD

**Issue by masterchop** [samtap/fang-hacks#353]

**Comment by masterchop** [comment]
i found that we can apply OpenCV (motion detection, face detection,  to the the RSTP feed that comes from the cam, ofcourse you need another hardware to do it as the camera is super low power, i am using a raspberry pi that works fine the problem is that the camera doesnt have IR vision, for some reason the scripts arent working for me but ill keep testing.

**Comment by matulekpl** [comment]
> i found that we can apply OpenCV (motion detection, face detection, to the the RSTP feed that comes from the cam, ofcourse you need another hardware to do it as the camera is super low power, i am using a raspberry pi that works fine the problem is that the camera doesnt have IR vision, for some reason the scripts arent working for me but ill keep testing.

Did You managed to run IR vision??

**Comment by masterchop** [comment]
yes, sorry.  I am doing OpenCV and everything already.

**Comment by Dylantje** [comment]
Dear.. Do you have a how to? Or perhaps what home automation system u use? I will try to make a motion sensor working with fanghack
