### ISSUE TITLE
Feature request: NTP

### ISSUE THREAD

**Issue by cycloptux** [samtap/fang-hacks#38]
Hi,
I enabled time overlay on my RTSP stream and it's more than 1 month wrong.
I'm not sure if that's a way to adjust time without rebooting to cloud management, but even then, is there (or would it be possible to add) a NTP server to have it get the right time from a server (either on the internet or within the same subnet) on its own?
Thanks!

**Comment by samtap** [comment]
You can set the time on the status page, it runs ntpdate when you apply a new timezone. The cloud app is messed up, sets the wrong timezone and applies an offset to what's actually displayed in the overlay.
There's some drift so you could run ntpdate in a cronjob to keep it in sync.  
More info in [FAQ](https://github.com/samtap/fang-hacks/wiki/F.A.Q.#the-timezone-is-incorrect)
