### ISSUE TITLE
IS the hack working with the last firmware? 

### ISSUE THREAD

**Issue by capretto78** [samtap/fang-hacks#387]
I have firmware 3.3. 4.173. IS The hack working with this firmware?

**Comment by sunyinghao5438** [comment]
i don't think so

**Comment by nariox** [comment]
You have to downgrade it. The only way I found to do this is to open it up and connect it to and UART module

**Comment by capretto78** [comment]
I successfully downgraded the firmware (via SD card) after that I applied the hack.
Now it's ok! Thanks
