### ISSUE TITLE
Use network SSID containing spaces?

### ISSUE THREAD

**Issue by aronsjoberg** [samtap/fang-hacks#389]
I have a Xiaomi XiaoFang running the Fang hack. I can access the camera using my browser and WinSCP. The cameras FW is 3.0.3.56 (Linux XiaomiCube 2.6.35.12 armv5tejl GNU/Linux).

I have earlier had the camera connected to the Cloud option under the Network settings. I now want to connect using the Wireless Client option. My network SSID is "STORA HULTE ASUS". I can't find this SSID in the list. There is however a truncated SSID called "STORA". If I try to connect to this SSID I get an error message: "Sorry, ASUS encryption is not supported!".

![image](https://user-images.githubusercontent.com/30977669/48100147-653c0d80-e222-11e8-82b1-433df8acafce.png)

If I change the name for my network SSID to "STORAHULTEASUS" I can connect. Because all my other devices (including some hard to reach IP cameras and Sonoffs) are configured to use "STORA HULTE ASUS" I would like to avoid change the SSID permanently.

Is it possible to connect the camera in Wireless Client mode to a SSID containing spaces?

I can connect to the cameras file system using SSH but I don't know where the wifi SSID configurations are stored?

**Comment by janstadt** [comment]
I have a space in my SSID as well. What did you end up doing here? Hopefully the fix wasnt to change your SSID?
