### ISSUE TITLE
Enabling Mi cloud

### ISSUE THREAD

**Issue by Zlikster** [samtap/fang-hacks#4]
Hi, first of all thanks for the effort to make this little cam more useable. Few questions.

- any option to leave Xiaomi cloud enabled without compromising other stuff? 
- I think if the Xiaomi cloud is enabled, it will write mp4 files (if enabled in Mi app) to the FAT32 partition, so i guess i should make FAT32 partition larger than 100MB (and leave ext2 part small)?

EDIT:

So i have made vfat partition a large one (left ext2 part @ 150MB). Telnet, ftp works, but i can't start rtsp server. Does Mi cloud has to be disabled for rtsp to work?

tried to start rtsp via telnet. 

/media/mmcblk0p2/data/usr/bin # ./snx_rtsp_server
Video source = /dev/video1
Cannot open '/dev/video0': 16, Device or resource busy

I can start rtsp when i disable cloud tho. Can we have both mi cloud and rtsp enabled, like on Mi Ants cam?

thank you!

**Comment by samtap** [comment]
As far as I know it's not possible. The cloud app claims the hardware and so does the rtsp server. The device crashes when I start the cloud app manually.

I think most people are interested in getting rid of the cloud apps, though I would like to keep a mode where cloud app is still functional (but you'll not be able to use rtsp server at the same time).
