### ISSUE TITLE
Cant open status page 

### ISSUE THREAD

**Issue by ijalsudekat** [samtap/fang-hacks#406]
Hi, 
i already hear 'hack' sound but why i cant open status page? i use xiaofang in the same router with my PC. and i can ping 192.168.3.101 with reply
btw i use latest firmware. does fanghack work with latest firmware? 

![image](https://user-images.githubusercontent.com/20786822/51797246-76e5ed80-2232-11e9-9537-6065e0f4ff16.png)

![image](https://user-images.githubusercontent.com/20786822/51797156-08ecf680-2231-11e9-8a6d-f8eace5481c2.png)

**Comment by DomolinBolivia** [comment]
You managed to find the solution, I have the same problem.

**Comment by umairyounus** [comment]
I'm facing the same issue.

**Comment by mudasar8k** [comment]
I am also facing the same issue.

**Comment by vincentkedison** [comment]
I am also facing the same issue.

**Comment by ijalsudekat** [comment]
i think my device not support anymore
https://github.com/samtap/fang-hacks/issues/402
