### ISSUE TITLE
OpenDir failed - hello.cgi

### ISSUE THREAD

**Issue by tarat73** [samtap/fang-hacks#41]
Hello,

Thank you for your effort.
I have got this camera yesterday from Gearbest.
I connected with MiHome, but it is a security risk.
I would like to install your solution.
I have created a Pendrive by your description and image (V 0.2). I checked the drive with Linux and it seems like correct.
I booted the camera and after the blue constant light I inserted the PenDrive.
The message from http://192.168.1.33/cgi-bin/hello.cgi -> OpenDir faile
The message from http://192.168.1.33/cgi-bin/status: 404 Not Found
Could you help me?

Thanks,

Attila

**Comment by ephestione** [comment]
You are supposed to use an sd card, not a pendrive

**Comment by tarat73** [comment]
Thank you.
I inserted the SD card but the problem is te same as I described before :(
Do you have any other idea?

**Comment by tarat73** [comment]
OK. Success.
I restarted the camera and the next restart fixed the problem. Sorry
