### ISSUE TITLE
Procedure to downgrade 5.6.2.35 "Xiaomi Mijia Xiaofang 1S" camera?

### ISSUE THREAD

**Issue by amit-nz** [samtap/fang-hacks#450]
I just got my hands on one of these, and I'm wanting to use it with Frigate so RTSP feed is all I need.

I found fang-hacks and tried wrote the image to sd, put the SD into the camera after it booted, heard the "Ting ting" sound, but going to `deviceip/cgi-bin/status` or to `deviceip/cgi-bin/hello.cgi` doesn't work (connection reset). 

The firmware on my device is 5.6.2.35 - but the guides I've seen (from 2017) appear to have people using firmware versions 3.0.3.56

So I went hunting, found a source for the 3.0.3.56 firmware, and a guide which simply amounts to - format a SD Card to FAT32, drop the contents ([google drive link](https://drive.google.com/file/d/1lw8jdW-y38Hque-hcUmi45PAEE8Vcbdq/view)) into the root of it, poweroff the camera, press & hold reset button, power it back on and then wait until the camera starts talking in chinese and that should be it.

I did this however my camera is still on 5.6.2.35

Is there a guide on how to do this properly? Perhaps I am missing a step? I don't mind cracking this thing open and soldering wires if I have to, but obviously if there's an easy way out to downgrade (or get this camera throwing RTSP out) I'd take that instead!

My camera's MAC is `44:23:7C:XX;XX:XX` and according to the box, the date of manufacture is 2019.09

**Comment by kiddyfurby** [comment]
In case you haven't already figured out, the 1s uses a different chip, try https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks
