### ISSUE TITLE
Problem running the RTSP

### ISSUE THREAD

**Issue by TamerLanTK** [samtap/fang-hacks#48]
Hey. I have a problem running the RTSP.  How to fix the problem?
![0503](https://cloud.githubusercontent.com/assets/26206963/23591044/f1020610-01f2-11e7-8e74-926e2e536041.PNG)

**Comment by simoneluconi** [comment]
Hi! it's the problem that i had. You need to disable the cloud app first (run 00-stop-cloud) and then run the rtsp-server. But you shouldn't have the network error :/ Maybe you also have misconfigured some network configuration.

**Comment by TamerLanTK** [comment]
when I start the script (00-stop-cloud), I get the message
`Running script '00-stop-cloud'...
/media/mmcblk0p2/data/etc/scripts/00-stop-cloud: source: line 3: can't open '/etc/fang_hacks.cfg'`

**Comment by samtap** [comment]
I've no idea how you ended up in this situation... If you remember please list all steps leading up to this. You did click the "apply" button on the status page to enable the hacks, right?

**Comment by Spartacus-6** [comment]
I'm stuck ???

Ran stop script - Running script '00-stop-cloud' but can't disable cloud ???

![5](https://cloud.githubusercontent.com/assets/26284102/23717862/dab4a2d0-040b-11e7-874b-69ed056c0650.PNG)

**Comment by Spartacus-6** [comment]
![6](https://cloud.githubusercontent.com/assets/26284102/23718162/ddc5bfbc-040c-11e7-9d97-ec6ad89d0390.PNG)

**Comment by samtap** [comment]
This isn't going anywhere. If you really think there's a bug, open a new issues and
**include a thorough description of your problem and the steps you've taken to get there**

If you're just looking for support because you're in over your head, go to discord and ask for help.
