### ISSUE TITLE
Whats wrong with Filesystem

### ISSUE THREAD

**Issue by SatoshiNakamoto** [samtap/fang-hacks#54]
Hi, i dont understand, what wrong.
Based, MBR, parts are logical

First partition FAT32(Active), Second Ext2. After reboot and insert SD-card, 
http://192.168.1.79/cgi-bin/hello.cgi
System Volume Information

time_lapse

record

log_286C077AD928_s.txt

bootstrap

snx_autorun.sh

http://192.168.1.79/cgi-bin/status
404 Not Found
The requested URL /cgi-bin/status was not found on this server.

**Comment by ZeroPoints** [comment]
How long did you wait before you inserted the SD after starting the cam? Did you wait till the blue light had stabilized?

**Comment by SatoshiNakamoto** [comment]
yes of course... i read your man

**Comment by ZeroPoints** [comment]
If you are having trouble getting it to work with the steps in the readme. Try flashing the supplied image instead of doing the manual method https://github.com/samtap/fang-hacks/releases

**Comment by SatoshiNakamoto** [comment]
Thank's, replace with .img :) zip Embarrasses
