### ISSUE TITLE
securityspy mac os

### ISSUE THREAD

**Issue by ageorgios** [samtap/fang-hacks#55]
I have SecuritySpy on Mac OS X and although I can view the stream with VLC at rtsp://ip/unicast I do not know the profile settings that SecuritySpy demads.

Has anyone succeeded with SecuritySpy and Xiaofang?

**Comment by samtap** [comment]
I'm sorry I have no access to a Mac OS X machine so I'm unable to test. You may get better response by asking around in the discord chat.

**Comment by ravarelab** [comment]
Did you succeed? I am interested in the same issue.

**Comment by ageorgios** [comment]
unfortunately no, I am using Xeoma that works ok, but I would like to work on security spy though

**Comment by ravarelab** [comment]
Thanks for your reply.

**Comment by bbbenji** [comment]
Attempted and failed. Don't think its compatible.
