### ISSUE TITLE
Can this project be a Project like openwrt ?? - Opensource linux Distribution (Firmware) for Wrt54GL and now dozens of router

### ISSUE THREAD

**Issue by Acharyapr** [samtap/fang-hacks#57]
Dear Samtap and  other contributors, 
Please Give Open Freedom to this camera by releasing opensource firmware for Cube/Spot camera.  As [OpenWrt ](https://openwrt.org/)is a Router Firmware which entirely replaces company's original firmware (For selected Hardware) i am using it on wrt54gl since 10 years...
In Every Device With default firmware everything is restricted and locked, you can't even know the MHz of processor and Size of Memory.

**Comment by SatoshiNakamoto** [comment]
Great Idea!

**Comment by samtap** [comment]
No, it doesn't make sense.
