### ISSUE TITLE
Need help on updating the xiaofang

### ISSUE THREAD

**Issue by con4n007** [samtap/fang-hacks#64]
I have installed fanghacks_v0.0.1.img successfully using Win32 Disk Imager.

now my question is how do i update to 0.20?

I cant access both USB partition to copy the files on Windows. I can only access the partition that has bootstrap folder and snx_autorun.sh

**Comment by samtap** [comment]
Just write the new image and use the update button on the status page, as explained here: https://github.com/samtap/fang-hacks/releases/tag/0.2.0

**Comment by con4n007** [comment]
the v0.20 is fanghacks_v0.2.0.zip, not an image file O_O
