### ISSUE TITLE
MiHome not working when patch enabled.

### ISSUE THREAD

**Issue by mexusbg** [samtap/fang-hacks#70]
MiHome says that device is offline when hacks are enabled.
Network is running. ps doesn't show iCamera as running.
Disabling the hack and MiHome works. Is it possible to have dropbear running and using MiHome app?

**Comment by samtap** [comment]
Yes, you just can't have rtsp server + cloud app running at the same time. There's a script that stops the cloud app after boot. If you disable that, the app keeps running and you can connect with mi home.

**Comment by smartynov** [comment]
I think this should be added to docs/faq. I spent couple of hours trying to make it work until I found this issue.
