### ISSUE TITLE
Partitions on SD Card

### ISSUE THREAD

**Issue by TDPFlorida** [samtap/fang-hacks#81]
I use the image supplied to CREATE the partitions/files on the SD Card. (I'm using a 32G SD) Everything works fine but when I deselect "Hacks enabled" <APPLY> and <REBOOT> in the MiHome APP it shows only .1G available on the SD card. I've tried expanding the first partition to include the rest of the SD card but once I do that RTSP no longer works (all the FangHacks I'm guessing.) Is there a way to increase the only visible partition so its not wasted?
Thanks

**Comment by samtap** [comment]
If you're not happy with the default partition layout you can use a partition manager to change it. For Windows, [MiniTool Partition Wizard](https://www.partitionwizard.com/free-partition-manager.html) works well

**Comment by Dylantje** [comment]
Sorry for the newbie question...
I did create no portion just flash the image to my sd... 
What are the thing[s] that i cannot use when i do this?

**Comment by TDPFlorida** [comment]
I can just tell you what happened with me when I flashed the SD card with the image provided I was able to bring up the FangHacks URL:
Hacks enabled:
•	RSTP works
•	MiHome (iPhone APP does NOT work with APP features like Recording etc.)
•	NO timestamp on RSTP
Hacks NOT enabled:
•	No RTSP
•	MiHome (iPhone APP does work with APP features like Recording etc.)
•	Timestamp appears in MiHome APP

My problem now is I am using a 32G SD card and when I apply the image to the SD card. MiHome shows the SD card as having .1G so MiHome sees no other partition that the first one. When I use "EPM", I can put all the space in the first partition BUT RTSP no longer works.

I will try using the "MiniTool Partition Wizard" and see if that works.

Any assistance provided would be appreciated!!!

**Comment by TDPFlorida** [comment]
I used "MiniTool Partition Wizard" and had 2 partitions: FAT32 (expanded to include all of remaining SD card) and Ext2 (150MB.) That seemed to fix my problems because when I enable the FangHacks, the RTSP works and when the FangHacks are disabled, most of the SD shows up in the MiHome APP. Now if I could just view the data stored on the SD card while its in the camera via the local network?
Thanks samtap!!!
