### ISSUE TITLE
RTSP Server does not start and other strange behaviour

### ISSUE THREAD

**Issue by Biggsis** [samtap/fang-hacks#89]
I created an SD card with the latest image, it reads and starts. 
I can start all other servers successfully (at least says so in the status page), but I cant start the RTSP server at all. Whenever I click on the start button, the page updates and says "Starting RTSP server..." but nothing happens. The server status displays a red NOK. Any ideas here?
I noticed another strange thing: In the status page it always tells me "Reboot required to apply new partition layout!", although I rebooted the camera several times already, it keeps telling me the above message...
Thanks

**Comment by bbbenji** [comment]
Been answered before.

https://github.com/samtap/fang-hacks/wiki/F.A.Q.
https://github.com/samtap/fang-hacks/issues/60#issuecomment-286468300
