### ISSUE TITLE
data directory not found

### ISSUE THREAD

**Issue by senovr** [samtap/fang-hacks#93]
Hi, 
I am using pre-build image for installation.
when I hit apply button, it installs scripts.
But, at the same time I have the following error:
Script is already installed!
Error: No 'data' directory found in /media/mmcblk0p2! 
 Hacks enabled 
 Disable cloud applications 

Any suggestions?

Second question- how I can resize the ext2 partition?
I am unable to find any "resize" button in web interface.
Thanks!

**Comment by samtap** [comment]
Probably your sdcard is corrupted by a failed resize attempt, or defective. You can try writing the image to a different card. If the scripts are already copied you can't apply the hack. If you choose to resize on the status page, you must wait for it to complete after a reboot. While it is in progress the data partition isn't mounted and you'll get the error. You'll see resize2fs in the process list.
If you still have issues please join discord chat.
